// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVlo0fOQEuHJHvoZwiXGC6kFMvbBSix9c',
    appId: '1:1019931084341:web:bb56a5b1ad46e3c0fe537c',
    messagingSenderId: '1019931084341',
    projectId: 'hotelreservation-d3913',
    authDomain: 'hotelreservation-d3913.firebaseapp.com',
    storageBucket: 'hotelreservation-d3913.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq2XwY_HNXH7Z1DAYlO5puFAfbY4y9sDM',
    appId: '1:1019931084341:android:c016e2fe7bf2cd64fe537c',
    messagingSenderId: '1019931084341',
    projectId: 'hotelreservation-d3913',
    storageBucket: 'hotelreservation-d3913.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAroUTHcNQ3i22nY3j-6DOH_AoHizHXVHc',
    appId: '1:1019931084341:ios:8ebd128472a0b540fe537c',
    messagingSenderId: '1019931084341',
    projectId: 'hotelreservation-d3913',
    storageBucket: 'hotelreservation-d3913.appspot.com',
    iosBundleId: 'com.example.hotelReservationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAroUTHcNQ3i22nY3j-6DOH_AoHizHXVHc',
    appId: '1:1019931084341:ios:52b2c44470da6d6afe537c',
    messagingSenderId: '1019931084341',
    projectId: 'hotelreservation-d3913',
    storageBucket: 'hotelreservation-d3913.appspot.com',
    iosBundleId: 'com.example.hotelReservationApp.RunnerTests',
  );
}
